package com.tobias.server.uno.command;

public enum CommandType {
    GAME_SETCARD,
    GAME_REQUESTCARD,
    GAME_UNO,
    GAME_DISCONNECT,
    GAME_START,
    GAME_REGISTEROPPONENTPLAYER,
    GAME_SETTOPCARD,
    GAME_SETDECKCOUNT,
    GAME_SETOPPONENTPLAYERCARDCOUNT,
    GAME_SETCARDSONTABLECOUNT,
    GAME_SETNEXTTURN,


    CLIENT_CONNECT,
    CLIENT_POLL,
    CLIENT_READY,
    CLIENT_REGISTERID,
    CLIENT_DISCONNECT,


    WORKER_UNKNOWNCOMMAND
}
